### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by surajmandalcell** [Gh0stExp10it/Flow.Launcher.Plugin.Ollama#14]
Can it show its output in flow launcher preview window if possible(f1)

Thanks

**Comment by Gh0stExp10it** [comment]
Thanks for the suggestion! I'll have a look at the sources when I have some spare time and then share some more info.

**Comment by Gh0stExp10it** [comment]
@surajmandalcell - please check the info in #15 
I've pushed a new release. This should be officially available through Flow-Launcher soon. Either check for updates in the settings under Plugin Store or run the command ```pm update Ollama``` directly.
